/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const FO: typeof import('./lib/state')['FO']
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const blur: typeof import('svelte/transition')['blur']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const crossfade: typeof import('svelte/transition')['crossfade']
  const derived: typeof import('svelte/store')['derived']
  const draw: typeof import('svelte/transition')['draw']
  const fade: typeof import('svelte/transition')['fade']
  const fly: typeof import('svelte/transition')['fly']
  const get: typeof import('svelte/store')['get']
  const getAllContexts: typeof import('svelte')['getAllContexts']
  const getContext: typeof import('svelte')['getContext']
  const hasContext: typeof import('svelte')['hasContext']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const readable: typeof import('svelte/store')['readable']
  const scale: typeof import('svelte/transition')['scale']
  const setContext: typeof import('svelte')['setContext']
  const slide: typeof import('svelte/transition')['slide']
  const tick: typeof import('svelte')['tick']
  const useHi: typeof import('./lib/state')['useHi']
  const writable: typeof import('svelte/store')['writable']
}
