// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const ASwitch: typeof import("@rgossiaux/svelte-headlessui")["Switch"]
    const Counter: typeof import("./components/nest/Counter.svelte")["default"]
    const Header: typeof import("./components/nest/Header.svelte")["default"]
    const Switch: typeof import("@rgossiaux/svelte-headlessui")["Switch"]
}

export {}
