// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Button: typeof import("./components/button.svelte")["default"]
    const Checkbox: typeof import("./components/checkbox.svelte")["default"]
    const FButton: typeof import("flowbite-svelte")["Button"]
    const FormCheckbox: typeof import("./components/form/checkbox.svelte")["default"]
    const GradientMonochromeButton: typeof import("flowbite-svelte")["GradientMonochromeButton"]
}

export {}
