// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Counter: typeof import("./lib/Counter.svelte")["default"]
    const Header: typeof import("./lib/header/Header.svelte")["default"]
}

export {}
